### ISSUE TITLE
privacy api class doesn't look correct.

### ISSUE THREAD

**Issue by danmarsden** [justinhunt/moodle-atto_cloudpoodll#2]
Looks like you have implemented the null provider, but I'm pretty sure you should be using external_location_link 
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

**Comment by justinhunt** [comment]
Indeed. This needed to be done. Thanks. Fixed in:
 https://github.com/justinhunt/moodle-atto_cloudpoodll/commit/8fdb9fc2d5f0e61d5ccd42e5588407a824531c46
