### ISSUE TITLE
Code precheck failures in plugins db

### ISSUE THREAD

**Issue by danmarsden** [justinhunt/moodle-atto_cloudpoodll#3]
Would be good to tidy those up a bit - particularly licence mising/ MOODLE_INTERNAL checks missing etc.

You might consider adding travis-ci support to get some of these failures shown on git commits too...

**Comment by justinhunt** [comment]
Thanks. I have fixed up the missing MOODLE_INTERNAL and missing licenses.  https://github.com/justinhunt/moodle-atto_cloudpoodll/commit/8fdb9fc2d5f0e61d5ccd42e5588407a824531c46
