### ISSUE TITLE
Consider documentation for sites that implement CSP policies.

### ISSUE THREAD

**Issue by danmarsden** [justinhunt/moodle-atto_cloudpoodll#4]
You may want to include information in your readme to state  that your plugin makes calls to https://cloud.poodll.com and  https://maxcdn.bootstrapcdn.com - (particularly the 2nd one which will not be obvious to people until they install your plugin and test it.)

**Comment by justinhunt** [comment]
Thanks. This has been addressed in: https://github.com/justinhunt/moodle-atto_cloudpoodll/commit/8fdb9fc2d5f0e61d5ccd42e5588407a824531c46
